### ISSUE TITLE
SlimPeriodTracker

### ISSUE THREAD

**Issue by ethanbanker** [SlimRoms/vendor_slim#18]
i saw someone by the name of "alex cruz" mention a slim period tracker, this could be really useful to me since i sometimes get my days mixed up :100: but i checked the git and vendor and it doesnt build it...can someone help

**Comment by valiantshadow** [comment]
Griffin is working on it, he has the same issue.

**Comment by valiantshadow** [comment]
He isn't salty, its just that time of the month.

**Comment by ethanbanker** [comment]
he could use his so called "ThemeManager" as a tampon till we fix this issue...all its good for anyways
