### ISSUE TITLE
This ROM is too awesome

### ISSUE THREAD

**Issue by dexter93** [SlimRoms/vendor_slim#3]
title says it all. Gratz guys :)

**Comment by vishnumad** [comment]
Yes, this is a serious issue. Hopefully this bug will be fixed soon.

**Comment by PBOVERHUIS** [comment]
Where can i get these ROMS?

**Comment by MSF-Jarvis** [comment]
I completely agree with @VishnuMadhusoodanan. I mean, I just blew through three server trials trying to get it built
